- menu_name: "Services"

- name: "How to Document"
  url: "https://cse-software.github.io/Howto/index.html"
  title: "How to Document"

- name: "Effective Software"
  url: "https://collegeville.github.io/Lex/"
  title: "Lex project: Effective Software"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"
